# Generated by Django 4.2.26 on 2025-11-11 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название меню', max_length=100, verbose_name='Название меню')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для вызова в шаблоне, например: main_menu', max_length=100, unique=True, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(blank=True, help_text='Явный URL, например: /about/', max_length=200, verbose_name='URL')),
                ('named_url', models.CharField(blank=True, help_text='Имя URL из urls.py, например: home', max_length=100, verbose_name='Именованный URL')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tree_menu.menu', verbose_name='Меню')),
                ('parent', models.ForeignKey(blank=True, help_text='Оставьте пустым для пункта верхнего уровня', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tree_menu.menuitem', verbose_name='Родительский пункт')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['order', 'id'],
            },
        ),
    ]
